### ISSUE TITLE
[WASM] - Localization with x:Uid not working with new Project Template

### ISSUE THREAD

**Issue by mnikonov** [unoplatform/uno#11462]
### Current behavior

The localization string not applied to xaml properites with x:Uid attribute when used new Project Template (updated solution template without using a Shared project)

**Steps  to reproduce** 

Add next values to resw file that located in library

Key: Text.Text
Value: Teeeeeesssssttt

Define next xaml 

`
<Grid>
        <TextBlock x:Uid="Text" Text="Hello, world!" Margin="20" FontSize="30" />
    </Grid>
`

Current behaviour

When run WASM project would be displayed 'Hello, world!'

### Expected behavior

When run WASM project displayed 'Teeeeeesssssttt'

### How to reproduce it (as minimally and precisely as possible)

Please find an example of issue in attached project

[App.zip](https://github.com/unoplatform/uno/files/10832205/App.zip)

In example, windows wersion of project works as expected

### Works on UWP/WinUI

None

### Anything else we need to know?

Can you provide workaround or code sample that demonstrates how to connect resources located in external library?

**Comment by jeromelaban** [comment]
Thanks for the report. This should have been fixed in 4.7.44. Can you upgrade to latest build and let us know ?

**Comment by mnikonov** [comment]
The issue still has place for 4.7.44. Please check example in archive, there I have updated all assemblies to latest version
[App.zip](https://github.com/unoplatform/uno/files/10836028/App.zip)

**Comment by jeromelaban** [comment]
Thanks for the test. 

You'll notice that when running the app on Windows `/App2/Text` is not working either. That's because WinUI does not support accessing resources this way.

To access resources from the `App2` class library project, you'll need to use:
```xaml
<TextBlock x:Uid="Text" Text="Hello, world!" Margin="20" FontSize="30" />
```

without the prefix. You'll also need to upgrade to 4.7.44 for it to work properly.

**Comment by mnikonov** [comment]
@jeromelaban  In second example, that was provided in comment, '/App2/Text' was replaced with'Test'. 

```xaml
<Page
    x:Class="App2.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"    
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <TextBlock x:Uid="Text" Text="Hello, world!" Margin="20" FontSize="30" />
    </Grid>
</Page>
```

Also all packages was updated to 4.7.44 
![image 4](https://user-images.githubusercontent.com/10001265/221664218-fab5d835-b7c8-4cbc-b58f-6eeda56eb667.jpg)

Result in WSAM project 
![image 5](https://user-images.githubusercontent.com/10001265/221664703-e829c35d-c349-4c03-8aca-0642305b2337.jpg)

**The issue was not fixed !!!! And bug should be reopened**

**Comment by jeromelaban** [comment]
Thanks. Does it work on windows with the same code?

**Comment by mnikonov** [comment]
yes

![image 6](https://user-images.githubusercontent.com/10001265/221669421-bd2bdec5-a401-4774-b063-38fcfca81b48.jpg)

**Comment by jeromelaban** [comment]
Thanks. I'm not reproducing locally, which means there's something different in the sample. We'll investigate.

**Comment by jeromelaban** [comment]
Can you try adding the following block to your `App2` project?

```xml
<PropertyGroup>
		<PriResource Include="**\*.resw" />
</PropertyGroup>
```

**Comment by jeromelaban** [comment]
Thanks. `ItemGroup` nodes should be located at the project level, like the other nodes in the file. You can safely put it at the end, like this.

```xml
   <ItemGroup>
        <PRIResource Include="**\*.resw" />
  </ItemGroup>
</Project>

**Comment by mnikonov** [comment]
Thanks for quick reaction
