### ISSUE TITLE
[WASM] Can't drag `Slider` with touch 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#12044]
### Current behavior

When trying to drag the Slider I noticed that it didn't behave properly. Sometimes it does move in the right direction but very slowly, sometimes it gets stuck and sometimes it goes the opposite direction. Edge sometimes shows the controls for going back when sliding (visible on the video bellow). This happens on all targets except for WinUI/UWP

https://user-images.githubusercontent.com/78549750/233867852-417931fb-8918-40ac-b9dd-dbf9e0acb1e9.mp4

### Expected behavior

The Slider should be draggable as on any other platform and mostly with mouse too.

### How to reproduce it (as minimally and precisely as possible)

This issue doesn't seem to be replicable in Playground as it works fine there. But go to https://gallery.platform.uno or https://toolkitlabs.dev/ and try to drag a Slider with touch.

### Works on UWP/WinUI

Yes

### Affected platforms

All targets except Windows.

**Comment by nguyeenvy** [comment]
This issue seems to have been resolved. It is no longer a problem on WASM.

**Comment by MartinZikmund** [comment]
This is still a problem, at least in Microsoft Edge on Windows (and I presume all browsers with gesture based navigation) - trying to slide the `Slider` also triggers the back navigation gesture and it is very easy to navigate away from the Uno application completely

![slider](https://github.com/unoplatform/uno/assets/1075116/d8c00694-f95d-46cf-8445-46c20217e483)

**Comment by Youssef1313** [comment]
Fixed with https://github.com/unoplatform/uno/pull/14132
