### ISSUE TITLE
Binding TextBlock's TextDecorations property in template crashes on WASM

### ISSUE THREAD

**Issue by Avid29** [unoplatform/uno#12929]
### Current behavior

TextBlocks dependent on binding to ``TextDecorations`` property will not render, and will throw the following warnings

``System.ArgumentOutOfRangeException: No strategy registration for conversion 'TextDecorations' to 'UInt32' (Parameter 'extensionPoint') at Uno.Conversion.DefaultConversionExtensions.To(Object value, Type toType, CultureInfo culture) in /home/vsts/work/1/s/src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Conversion/DefaultConversionExtensions.cs:line 85``

### Expected behavior

TextBlocks dependent on binding to ``TextDecorations`` property should render with all flagged text decorations.

### How to reproduce it (as minimally and precisely as possible)

An example can be found in the MarqueeText for the Windows Community Toolkit.

https://github.com/CommunityToolkit/Labs-Windows/blob/3670f485c0a913d42ac04a898de6f49f658a8390/components/MarqueeText/src/MarqueeText.xaml#L86

The control will not display on WASM, unless you remove lines 86 and 96 from ``MarqueeText.xaml``

### Workaround

Remove TextDecorations bindings

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI: 4.6.18 and 4.9.26

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.6.5

### Anything else we need to know?

https://github.com/CommunityToolkit/Labs-Windows/issues/452

**Comment by jeromelaban** [comment]
Thanks for the report. I believe this was fixed in Uno builds later than 4.6. Could you try again with an updated version of Uno?

**Comment by Avid29** [comment]
I just tried updating to ``4.9.26``. The same issue is still present.

**Comment by jeromelaban** [comment]
Thanks for the validation. Would you have a sample that shows the control use that causes this behavior?

**Comment by Youssef1313** [comment]
`DefaultConversionExtensions` was removed in https://github.com/unoplatform/uno/pull/12700, though this bug still persists.

I can reproduce it in a new uno app simple with the following code:

```csharp
public sealed partial class MainPage : Page
{
    public TextDecorations P1 { get; set; }

    public MainPage()
    {
        this.InitializeComponent();
    }
}
```

```xml
<TextBlock Text="Hhhh" TextDecorations="{Binding P1}" />
```

The stack trace is:

```
      System.InvalidOperationException: Failed to load UnoApp1.MainPage: System.NotSupportedException: UInt32Converter cannot convert from Windows.UI.Text.TextDecorations.
         at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
         at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
         at Uno.UI.DataBinding.BindingPropertyHelper.ConvertUsingTypeDescriptor(Type type, Object value) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1365
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1399
         at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass40_9.<InternalGetValueSetter>b__13(Object instance, Object value) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1011
         at Windows.UI.Xaml.Data.BindingExpression.SetTargetValue(Object value) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingExpression.cs:line 427
         at Windows.UI.Xaml.Data.BindingExpression.ApplyFallbackValue(Boolean useTypeDefaultValue) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingExpression.cs:line 345
         at Windows.UI.Xaml.Data.BindingExpression..ctor(ManagedWeakReference viewReference, DependencyPropertyDetails targetPropertyDetails, Binding binding) in C:\Users\PC\Desktop\uno\src\Uno.UI\DataBinding\BindingExpression.cs:line 137
         at Windows.UI.Xaml.DependencyPropertyDetailsCollection.SetBinding(DependencyProperty dependencyProperty, Binding binding, ManagedWeakReference target) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.Bindings.cs:line 132
         at Windows.UI.Xaml.DependencyObjectStore.SetBinding(DependencyProperty dependencyProperty, BindingBase binding) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.Binder.cs:line 387
         at Windows.UI.Xaml.UIElement.SetBinding(DependencyProperty dependencyProperty, BindingBase binding) in C:\Users\PC\Desktop\uno\src\Uno.UI\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.UIElement_85915f7d6b7124464cf9d270ce415b49.cs:line 201
         at UnoApp1.MainPage.<>c.<InitializeComponent>b__9_5(TextBlock c0, MainPage __that, NameScope __nameScope) in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_5d6f09b760d3c360d52762395099dad7.cs:line 92
         at Uno.UI.Helpers.Xaml.ApplyExtensions.GenericApply[TType,TArg1,TArg2](TType instance, TArg1 arg1, TArg2 arg2, Action`3 apply) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Markup\ApplyExtensions.cs:line 58
         at UnoApp1.MainPage.InitializeComponent() in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_5d6f09b760d3c360d52762395099dad7.cs:line 69
         at UnoApp1.MainPage..ctor() in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1\MainPage.xaml.cs:line 11
         at UnoApp1.Skia.Gtk.MetadataBuilder_684.CreateInstance() in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1.Skia.Gtk\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs:line 24979
         at Windows.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 463
         at Windows.UI.Xaml.PagePool.DequeuePage(Type pageType) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\PagePool.cs:line 69
         at Windows.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 453
         at Windows.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 443
         at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 291
         at UnoApp1.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1\App.cs:line 49
         at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 295
         at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 284
         at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter) in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 279
         at UnoApp1.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1\App.cs:line 35
         at UnoApp1.AppHead.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\PC\Desktop\App1\UnoApp1\UnoApp1\UnoApp1.Base\AppHead.xaml.cs:line 30
         at Windows.UI.Xaml.Application.Initialize() in C:\Users\PC\Desktop\uno\src\Uno.UI\UI\Xaml\Application.skia.cs:line 98
         at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\Users\PC\Desktop\uno\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 343
```
