### ISSUE TITLE
"Ensure Event Failed" when generating event handler with "New Event Handler" option

### ISSUE THREAD

**Issue by riandika-lumaris** [unoplatform/uno#1348]
## Current behavior

When editing XAML file in VS 2019, generating event handler with "New Event Handler" options works for the first time, then it shows "Ensure Event Failed" after that. I need to close and reopen the xaml as the workaround.

## Expected behavior

The options should work without "Ensure Event Failed" error.

## How to reproduce it (as minimally and precisely as possible)

1. Open xaml file
2. Generate event handler in any component using "New Event Handler" option
3. Repeat step 2 again then error shown

## Environment

Nuget Package:

Package Version(s): 1.45.0

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.2)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Howdy @riandika-lumaris, this sounds like a bug in visual studio for windows. Can you please reproduce the problem and use the menus within Visual Studio to report it to Microsoft?

![image](https://user-images.githubusercontent.com/127353/62671112-df2f3c00-b9d8-11e9-9720-846dc4e13e91.png)


ps. Out of interest are you using a shared project?

**Comment by riandika-lumaris** [comment]
I don't think it is a bug from VS because the option works perfectly with pure UWP Solution.

And yes, there is a shared project because I use the uno extension to create the solution.

**Comment by ghuntley** [comment]
The "New Event Handler" functionality comes from VSWIN, I've got a hunch that you'd be able to reproduce this with a pure UWP solution that uses shared projects. So many things are changing under the hood of VSWIN at the moment. Typically, I'm raising 1 to 3 new feedback items every week. Uno has a meta ticket open at https://github.com/unoplatform/uno/issues/982, when you raise your feedback item can you please comment on it? Cheers.

**Comment by ghuntley** [comment]
Howdy @riandika-lumaris. I experienced this today and can confirm that it isn't a problem with Uno, it's a defect in vswin and shared projects. "Ensure Event Failed" appears when generating a new event handler on UWP when using Shared Projects. It does not happen when using a UWP class library.

Have opened https://developercommunity.visualstudio.com/content/problem/690015/uwp-ensure-event-failed-when-creating-new-event-ha.html. Could you drop on by and give it a 👍? Cheers.

**Comment by realivanjx** [comment]
is there any way to add event to controls from xaml?

**Comment by jeromelaban** [comment]
@realivanjx it depends on the version of visual studio, but recent ones, (e.g. VS 16.5 preview) seems to improve the situation.

**Comment by MikiraSora** [comment]
It still exist in vs2019 16.5

**Comment by yoshiask** [comment]
@jeromelaban This issue still exists in VS 2019 16.6. This is an incredibly annoying bug, and the issue over on Developer Community was closed just over a year ago with no solution or workaround.

**Comment by ElyasMTarek** [comment]
I started working with UNO today and ran into the same problem. Is there a workaround or do I need to write the handlers manually?

**Comment by jeromelaban** [comment]
@ElyasMTarek for now, no. There isn't a fix for this, though you can use the `{x:Bind}` event syntax for easier method authoring. See [this document](https://github.com/unoplatform/uno/blob/master/doc/articles/features/windows-ui-xaml-xbind.md) for details on how to use it.

**Comment by ElyasMTarek** [comment]
@jeromelaban Thanks for the advice. Hope this will get fixed in near future tho.

**Comment by NikoMontana** [comment]
I have the same problem, any updates to this?

**Comment by richkisic** [comment]
Bug is still in Visual Studio 2019 16.8. Agreed this is a very frustrating bug. 
![eef](https://user-images.githubusercontent.com/19941372/99555773-aed19e00-298e-11eb-80eb-2bbae0797e2e.PNG)

**Comment by rizaanlakay** [comment]
Please fix this. It is really annoying.

**Comment by MartinZikmund** [comment]
This problem is unfortunately caused by Visual Studio, please help us by sending feedback there and upvoting the linked issue in WinUI.

**Comment by jeromelaban** [comment]
This is fixed in our latest 4.7 templates, using .NET 7 and WinAppSDK,
