### ISSUE TITLE
[Mac Catalyst] UIKit Consistency error thrown when picking file

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno#15504]
### Current behavior

When calling `FileOpenPicker.PickSingleFileAsync` it throws:
![image](https://github.com/unoplatform/uno/assets/94198647/332ccffb-9fe5-4cdf-ac2b-4e9aa2977193)

### Expected behavior

`FileOpenPicker.PickSingleFileAsync` should open file picker correctly

### How to reproduce it (as minimally and precisely as possible)

Repro project: [MacIssue.zip](https://github.com/unoplatform/uno/files/14303060/MacIssue.zip)

1. Run repro
2. Click Pick File button

### Workaround

I tried using `UIKit.UIApplication.SharedApplication.InvokeOnMainThread` but I got the same result.

### Works on UWP/WinUI

None

### NuGet package version(s)

```
<PackageVersion Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageVersion Include="Geolocation" Version="1.2.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231219000" />

    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Core.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Authentication" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Authentication.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Configuration" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive.Messaging" Version="4.0.0" />

    <PackageVersion Include="Uno.Material.WinUI" Version="4.1.1" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.1.5" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="5.1.5" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.3.0" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="$(UnoVersion)"/>
    <PackageVersion Include="Uno.WinUI.DevServer" Version="$(UnoVersion)" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.10.0.2" />
    <PackageVersion Include="Mapsui.Uno.WinUI" Version="4.1.2" />
```

### Affected platforms

Mac Catalyst

### IDE

Visual Studio Code

**Comment by mcocaroUX** [comment]
@ajpinedam Thanks for your answer. As described on the [documentation](https://platform.uno/docs/articles/features/windows-storage-pickers.html#breadcrumb) those lines are needed in order to the code wont fail. 

I tested the code you sent and the outcome remains the same

**Comment by ajpinedam** [comment]
> @ajpinedam Thanks for your answer. As described on the [documentation](https://platform.uno/docs/articles/features/windows-storage-pickers.html#breadcrumb) those lines are needed in order to the code wont fail.
> 
> I tested the code you sent and the outcome remains the same

Thanks for the reply. Yes, I re-ran the sample you provided and was able to reproduce the issue you reported.

We pushed a fix yesterday, which should have already been merged and made available in one of the latest Uno versions.

cc: @mcocaroUX

**Comment by jeromelaban** [comment]
The backport is now available in 5.1.64.

**Comment by mcocaroUX** [comment]
@jeromelaban @ajpinedam This fix doesn't seem to be available on `5.1.64`, I'm still getting the same issue

**Comment by jeromelaban** [comment]
@mcocaroUX Can you provide a new stack trace of the issue?

**Comment by mcocaroUX** [comment]
@jeromelaban We solved it, it was some missing entitlement on our side. Thanks for your help!

**Comment by jeromelaban** [comment]
Thanks. Can you tell which entitlement you were missing? We may be able to enhance our docs with it.

**Comment by mcocaroUX** [comment]
Sure! [com.apple.security.files.user-selected.read-write](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_files_user-selected_read-write)
