### ISSUE TITLE
Skia Targets allows to change the UI on Background thread

### ISSUE THREAD

**Issue by pedrojesus-work** [unoplatform/uno#15879]
### Current behavior

If I try to edit a `TextBox.Text` on a Background thread that will work and the text will be updated.

### Expected behavior

Some exception saying that I can't change the UI outside the UIThread.

### How to reproduce it (as minimally and precisely as possible)

In order to run the issue, just try out this sample. IF you run the Windows target it will fail when the code hits `ContinueWith`, on Skia targets it will work.
[GTKUIBackgroundThread.zip](https://github.com/unoplatform/uno/files/14595016/GTKUIBackgroundThread.zip)

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

**Comment by jeromelaban** [comment]
@pedrojesus-work this is fixed in the latest 5.2 builds, background operations are blocked. Is this a version you tested with?

**Comment by pedrojesus-work** [comment]
@jeromelaban, no it's 5.1.87, I'll try the 5.2 and see how that goes

**Comment by pedrojesus-work** [comment]
Changed the sdk version to 5.2.0 `"Uno.Sdk": "5.2.0-dev.1921",` and still reproduce the error

**Comment by Youssef1313** [comment]
@jeromelaban The added check was in a specific code path that's known to be very problematic when accessed concurrently. It doesn't cover all `SetValue` calls, but only subset that end up calling `DependencyProperty.GetProperty` (e.g, it happens for inherited properties for example).

To fix this issue, the check will need to happen in `InnerSetValue`, but that's a larger breaking change than what was recently introduced. I'll open a PR anyway.
