### ISSUE TITLE
Align ActualWidth/ActualHeight behavior with WinUI

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#16120]
### Current behavior

Currently causing a bug for ShadowContainer that's being worked-around in https://github.com/unoplatform/uno.toolkit.ui/pull/1092

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
For future reference, for this case when the SKXamlCanvas is reading its ActualHeight, it doesn't have a layout storage for unknown reason.

![image](https://github.com/unoplatform/uno/assets/31348972/6a4e4617-274f-4340-b74a-9a389accfbf8)

**Comment by Youssef1313** [comment]
This should be fixed now

**Comment by morning4coffe-dev** [comment]
Reopening: this still reproduces on current bits, with a concrete case that the original fix does not appear to cover.

### What still diverges

On the Skia heads, `TextBlock.ActualWidth` returns `DesiredSize.Width` — the layout slot **including `Margin`** — instead of the rendered text extent.

Every element below is given the **same explicit `Width="200"`**:

| element | `Margin` | WinUI 3 `ActualWidth` | Skia `ActualWidth` | Skia `DesiredSize.Width` |
|---|---|---|---|---|
| `TextBlock` `"Hi"` | `0` | **13.33** | **200.00** | 200.00 |
| `TextBlock` `"A much longer piece of text"` | `0` | **171.08** | **200.00** | 200.00 |
| `TextBlock` `"Hi"` | `0,0,6,0` | **13.33** | **206.00** ⚠️ | 206.00 |
| `Border` | `0,0,6,0` | 200.00 | 200.00 ✅ | 206.00 |
| `Button` | `0,0,6,0` | 200.00 | 200.00 ✅ | 206.00 |
| `TextBox` | `0,0,6,0` | 200.00 | 200.00 ✅ | 206.00 |

Two distinct symptoms:

1. Two `TextBlock`s with **different text** but the same `Width` report an **identical** `ActualWidth` on Skia, while WinUI 3 reports the text extent (13.33 vs 171.08).
2. With `Width="200"` and `Margin="0,0,6,0"`, Skia reports `ActualWidth = 206`, i.e. **greater than the explicitly set `Width`**. `Margin` lies outside the element's own box, so this value is invalid independently of the text-extent question.

Note that on Skia `TextBlock.ActualWidth == DesiredSize.Width` in every row, which is what suggests `ActualWidth` is being sourced from the desired size rather than from the arrange/text-layout result.

### Scope

The defect is **specific to `TextBlock`**. `Border`, `Button` and `TextBox` with identical `Width`/`Margin` return the correct `200.00` on both platforms, so this looks narrower than the general layout-storage problem that was fixed here originally.

### Repro

Minimal repro (a `dotnet new unoapp --preset blank` app with two files replaced), including full instructions and the output from both heads:

https://gist.github.com/morning4coffe-dev/2c15f49ae5e5cfd153344dfddb85f0c3

It prints a table and self-diagnoses:

```
# Skia
different text, same Width -> same ActualWidth? YES (wrong)
ActualWidth exceeds explicit Width=200?         YES (wrong: 206.00)

# WinUI 3
different text, same Width -> same ActualWidth? no (correct)
ActualWidth exceeds explicit Width=200?         no (correct)
```

### Versions

Reproduced on both:

* `Uno.Sdk` **6.4.58**
* `Uno.Sdk` **6.7.0-dev.129** / `Uno.WinUI` **6.7.0-dev.815**

.NET SDK 10.0.302, Windows 11 26100, x64. Affected: Skia (Desktop).

### Why it matters

Found while porting [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon) to Uno. The ribbon emulates WPF's shared header column by measuring header `TextBlock`s; because `ActualWidth` reports the imposed slot rather than the text extent, header width computations diverge between the Skia and WinUI 3 heads. It is a common pattern to measure rendered text via a `TextBlock`'s `ActualWidth`, so this is easy to hit.

Happy to split this out into a separate issue if you'd prefer to keep this one scoped to the original `SKXamlCanvas` case.

**Comment by morning4coffe-dev** [comment]
Additional evidence — the same defect also affects **`ActualHeight`**, and reproduces **without any `Margin`** involved.

Same repro app, different `TextBlock` configurations (no `Margin` anywhere):

| `TextBlock` | WinUI 3 `ActualWidth` / `ActualHeight` | Skia `ActualWidth` / `ActualHeight` | Skia `DesiredSize` |
|---|---|---|---|
| `Text="Hello"` (no constraint) | 32.25 / 18.62 | 34.00 / 19.50 | 34.00 / 19.50 |
| `Width="120"` `TextWrapping="Wrap"` | **115.14** / 74.48 | **120.00** / 76.50 | 120.00 / 76.50 |
| `Width="120"` `TextTrimming="CharacterEllipsis"` | **112.83** / 18.62 | **120.00** / 19.50 | 120.00 / 19.50 |
| `MaxWidth="140"` `TextWrapping="Wrap"` | 125.42 / **55.86** | 132.50 / **57.50** | 132.50 / 57.50 |

On Skia, `ActualWidth == DesiredSize.Width` and `ActualHeight == DesiredSize.Height` in **every** case. On WinUI 3 both are consistently smaller than the desired size, because they describe the rendered text.

The wrapping case is the clearest illustration: with `Width="120"` and `TextWrapping="Wrap"`, WinUI 3 reports `ActualWidth = 115.14` — the width of the longest laid-out line — whereas Skia reports the full `120.00` slot. `TextTrimming` behaves the same way (112.83 vs 120.00).

So the underlying problem is not limited to the `Margin` case in my previous comment: `TextBlock.ActualWidth` / `ActualHeight` on Skia appear to be returning the element's desired/slot size rather than the text layout result. The `Margin` case is simply the variant where the resulting value is provably invalid (`ActualWidth = 206` with `Width="200"`).

For completeness, the following were checked in the same app and **match** across the two heads, so this looks specific to text layout rather than a general `ActualWidth` regression:

* `ScrollViewer` `ExtentWidth/Height`, `ViewportWidth/Height`, `ScrollableWidth/Height`
* `Grid` star sizing honouring `MinWidth`
* `Border` / `Button` / `TextBox` `ActualWidth` with an explicit `Width` and a `Margin`
* Automation peer types, control types and class names for `Button` / `TextBox` / `CheckBox`
* `Flyout` open/hide and flyout content `ActualWidth`/`ActualHeight`

Repro project (updated): https://gist.github.com/morning4coffe-dev/2c15f49ae5e5cfd153344dfddb85f0c3
