### ISSUE TITLE
[vscode] "Could no find task Uno*" on multi-rooted workspaces

### ISSUE THREAD

**Issue by yeahg-dev** [unoplatform/uno#17580]
Type: <b>Bug</b>

## Current Behavior
- I made a workspace for mobile. 
- I configured 2 type of launch for workspace on .code-workspace file 
```json
{
    "folders": [
      {
        "path": "DrawerControlSafeAreaTest.Mobile"
      }
    ]
    ,
    "launch": {
      "version": "0.2.0",
      "configurations": [
        {
          "name": "Launch Test with Custom Task",
          "type": "Uno",
          "request": "launch",
          // this task is defined in .vscode/task.json
          "preLaunchTask": "build Project"
        },
        {
          "name": "Launch Test with Uno Platform Task",
          "type": "Uno",
          "request": "launch",
          "preLaunchTask": "Uno: net7.0-android | Debug | android-x64"
        },
      ]
    }
}
  
```
- When I start debug with "Launch Test wiith Custom Task", nothing happens except this error alert is showing. 
- When I start debug with "Launch Test wiith Uno Platfrom Task", nothing happens except this error alert is showing. 
<img width="273" alt="스크린샷 2024-07-17 오후 3 50 37" src="https://github.com/user-attachments/assets/4302d928-554d-4795-b579-f4023e0d31ac">

## Expected Behavior
-  When start debug with "Launch Test with Custom Task", preLaunchTask "build Project" task should be excuted. 
-  When Start debug with "Launch Test with Uno Platform Task", preLaunchTask "Uno: net7.0-android | Debug | android-x64" task should be excuted. (As far as I know, this task belongs to Uno Platform Extension)
	
## How to reproduce it (as minimally and precisely as possible)
For build related issue consider attaching the .binlog file

## Workaround
"build Project" task referred by lauch.json work successfully in **"not workspace"**.
```json
{
  // Use IntelliSense to find out which attributes exist for C# debugging
  // Use hover for the description of the existing attributes
  // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
  "version": "0.2.0",
  "configurations": [

    {
      "name": "Launch in not workspace",
      "type": "Uno",
      "request": "launch",
      "preLaunchTask": "build Project"
    },
  ]
}
```

## Extension Status
Extension: Dev Kit Mode
Debugger: Ready
Hot-Reload: Running on port 61370
XAML LSP: Ready

## Environment information

* Platform: darwin 23.1.0 (arm64)
* VSCode version: 1.91.1
* dotnet version: 8.0.302
* C# Extension: 'ms-dotnettools.csharp' version 2.34.12
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.8.14
* Uno Extension: 'unoplatform.vscode' version 0.14.1
* Xcode version: Xcode 15.4 Build version 15F31d

Extension version: 0.14.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 11, 10|
|Memory (System)|32.00GB (3.56GB free)|
|Process Argv|--crash-reporter-id b84a933d-ae30-433b-abe7-a8314f276265|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31094925
refactorc:31098050
ccplti:31098112

```

</details>

**Comment by spouliot** [comment]
The Uno Platform extension provides its own tasks but otherwise it's VS Code that does the match up (between launch and tasks).

Can you attach a test case that demonstrate the issue ? and any other steps (like what's selected in the status bar). Thanks!

note: the mixup between net7.0 and net8.0 is weird

**Comment by yeahg-dev** [comment]
When Start Debug on not workspace, Uno Platforms's task run well.  but on workspace, I think VScode can not find Uno Platform's task. 

This is status bar selected.

- on not workspace
![스크린샷 2024-07-18 오전 10 18 15](https://github.com/user-attachments/assets/8a82606e-18ef-4647-8a84-7ba49fbc30b1)

- on workspace
![image](https://github.com/user-attachments/assets/a53468f2-b152-4795-82cd-e9b53a5680aa)

I uploaded the project to [this repo](https://github.com/yeahg-dev/VSCodeWorkspaceTaskTest). Please check it out

**Comment by jeromelaban** [comment]
@yeahg-dev could you give a try at the latest version we published last friday?

**Comment by yeahg-dev** [comment]
@jeromelaban 
- I tried to add package `Uno.WinUI 5.4.0-dev.1004`, But since I am using `Uno.SDK 5.1.50` Conflict has occured. 
- So I replaced `Uno.Sdk` with `msbuild sdk` of csproj files. and specify version of `WinUI` packages like this. Then the devices or simulator will not run.
```xml

<Project ToolsVersion="15.0">
  <!--
    Note that the $(UnoVersion) comes from the Uno.Sdk. You should not update it manually. To update the version of Uno,
    you should instead update the Sdk version in the global.json file.
    
    See https://aka.platform.uno/upgrade-uno-packages for more information.
  -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.240211001" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Core.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Configuration" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Material.WinUI" Version="4.1.1" />
    <PackageVersion Include="Uno.Dsp.Tasks" Version="1.2.9" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.1.5" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="5.1.5" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.3.0" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.4.0-dev.1004" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="5.4.0-dev.1004" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.4.0-dev.1004" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.4.0-dev.1004" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.10.0.2" />
  </ItemGroup>
</Project>
```


Did I misunderstood "latest version we published last friday"? 
or Is there any simple way to use `Uno.WinUI 5.4.0-dev.1004`(which is not compatible with Uno.SDK)?

**Comment by yeahg-dev** [comment]
Thanks! But It seems not fixed. 
still the same error is occuring
![image](https://github.com/user-attachments/assets/2d3f079c-e902-453f-8c76-9654f23308fb)

**Comment by jeromelaban** [comment]
Thanks. Can you take a picture of your vscode, particularly the page that opens when viewing the options of the uno platform extension?

**Comment by xperiandri** [comment]
There is just no docs how to configure it right. But I figured out how

**Comment by yeahg-dev** [comment]
@jeromelaban 
Here is screen capture of VScode.

Uno Extension Settings - User
![image](https://github.com/user-attachments/assets/c262b98c-053a-4c52-95a6-17008dfdc343)


Uno Extension Settings - Workspace
![image](https://github.com/user-attachments/assets/2975ff4f-acb3-460a-937c-c9b04e659aeb)

And this is User Task Command Palette on Test workspace
![image](https://github.com/user-attachments/assets/e54b7acc-10c8-4bb2-93c0-2e1c24f091fb)
![스크린샷 2024-08-02 오후 1 36 11](https://github.com/user-attachments/assets/3d3de6e4-4d5e-4ae4-a987-85f0c2370f6b)

**Comment by yeahg-dev** [comment]
> There is just no docs how to configure it right. But I figured out how

Oh Can you share the solution?

**Comment by spouliot** [comment]
@yeahg-dev sorry for the delay. I don't get quite the same results as you have described.

> When I start debug with "Launch Test wiith Custom Task", nothing happens except this error alert is showing.
> When I start debug with "Launch Test wiith Uno Platfrom Task", nothing happens except this error alert is showing.

Those names do not exist inside your repo.

What I noticed is that your repo seems to use an old Uno templates which has more than one solution, like:

* `DrawerControlSafeAreaTest.sln` and
* `DrawerControlSafeAreaTestMobile\DrawerControlSafeAreaTestMobile.sln` 

And based on your screenshots you're using the `*Mobile.sln` solution, which is not at the same level as the `.vscode` where your custom configuration resides.

When I use `DrawerControlSafeAreaTest.sln` then I do not have build failures.

When I use `DrawerControlSafeAreaTestMobile.sln` I do get build failures (but not alerts as you mentioned above).

What happens to you if you use the `DrawerControlSafeAreaTest.sln` solution file ?


Also, if possible, I suggest you to update to the latest **single project** templates so you'll have a better overall experience (with a single solution file). That _might_ fix your issue... but I can't be sure since I don't have the same errors as you did.

**Comment by xperiandri** [comment]
@yeahg-dev https://youtu.be/fr2bjB5KGb4
https://gist.github.com/xperiandri/3812bc86d2bef26c5ac8e1e5f8e62737

**Comment by spouliot** [comment]
@xperiandri hey, I'm not sure I'm following what you're suggesting ?

Your linked gist seems to be a copy of the [`launch.json`](https://github.com/unoplatform/uno.templates/blob/release/stable/5.3/src/Uno.Templates/content/unoapp/.vscode/launch.json) that is part of our templates (using `dotnet new ...` or our [online wizard](https://new.platform.uno). Am I missing something ?

Side note: except for web assembly, which requires more configuration, a `launch.json` file is not needed to build/debug Uno applications. Press F5 while a C# file is opened and it will build/deploy using the settings you selected (in the status bar).

**Comment by xperiandri** [comment]
@spouliot maybe it works for you and I would love to see a step-by-step guide to that.
But for my scenario of enterprise development where in one solution there may be multiple different runnable projects, I was not managed to successfully apply your approach. Maybe I did something wrong but till now no one made any explanation or tutorial for that.

**Comment by spouliot** [comment]
Hello @xperiandri 

> maybe it works for you and I would love to see a step-by-step guide to that.

From this [guide](https://platform.uno/docs/articles/get-started.html) you have separate step-by-step instructions for VS, VS Code and Rider with, where applicable, OS specific steps.

> But for my scenario of enterprise development where in one solution there may be multiple different runnable projects, I was not managed to successfully apply your approach.

We used, before Uno 5 and the single project support, to have several `.csproj` inside a solution. This is also quite common in the Uno git repository.

IMO the strangest part is that you're using the same `launch.json` file that our template provides. I would not expect one to work and the other to fail since the input would be the identical. Since it fails for you then there must be a difference somewhere...

> Maybe I did something wrong but till now no one made any explanation or tutorial for that.

Do you mind opening a [discussion](https://github.com/unoplatform/uno/discussions/new?category=q-a) to continue ?

I'd like to figure out what is the problem and, if required, update our code/docs. 

Also I'm not sure it's related to the original question where a `.code-workspace` file, for multi-root workspaces, is being used.

Thanks!

**Comment by yeahg-dev** [comment]
@spouliot 
Thank you for sharing and kind suggestion! 
But changing to single solution or single project will be not suitable for my product. Because the purpose of using workspace is to collect folders belonging to different solutions and work on them in a workspace.

>When I start debug with "Launch Test wiith Custom Task", nothing happens except this error alert is showing.
>When I start debug with "Launch Test wiith Uno Platfrom Task", nothing happens except this error alert is showing.
>>Those names do not exist inside your repo.

Oh I updated latest version 3 weeks ago. maybe you would open not latest version. In latest you could find "Launch Test wiith Custom Task", and "Launch Test wiith Uno Platfrom Task" when open "Test.code-workspace".
Could you check again with the latest version?

**Comment by spouliot** [comment]
> Because the purpose of using workspace is to collect folders belonging to different solutions and work on them in a workspace.

Yes but a `.code-workspace` file is a VS Code only feature, it consolidate various locations inside a single _virtual_ workspace of VS Code.

However it does not affect how the (dotnet) builds are done, `dotnet` is not aware of normal (or multi-rooted) workspaces. Now it's up to you but you should have no problem using a newer, single project Uno template.

> Could you check again with the latest version?

I double checked and I was using the latest version. I likely missed them because of copy/paste errors :) I copied the names from the issue, but they are not an exact match (typo) for the content of https://github.com/yeahg-dev/VSCodeWorkspaceTaskTest/blob/main/.vscode/Test.code-workspace#L21

For some reasons the Microsoft C# (and/or C# DevKit) extension(s) [1] does not load your project this morning, it just keeps spinning ?!?

<img width="235" alt="Screenshot 2024-08-20 at 10 36 20 AM" src="https://github.com/user-attachments/assets/e05cc249-85db-43cb-8391-e5541683bc98">

This works fine with other projects that I used and this is not something related to the Uno extension, I uninstall it to make sure of it.

Note that I am using the pre-release versions of the MS extensions. 

* C# Extension: 'ms-dotnettools.csharp' version 2.43.16
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.10.6

I'll try again with the stable releases.

**Comment by spouliot** [comment]
The project loads correctly when using the current stable releases

* C# Extension: 'ms-dotnettools.csharp' version 2.39.29
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.9.55

**Comment by spouliot** [comment]
Filled with Microsoft as https://github.com/dotnet/vscode-csharp/issues/7455

**Comment by spouliot** [comment]
I can duplicate the issue. Even if the extension register the task with every workspace I still get the error 😢 

This seems similar to https://github.com/microsoft/vscode/issues/192041 and MS answer is, at best, not very helpful (for the extension that normally provides the task definition).

Side note: adding a `.vscode` inside a multi-rooted workspace is likely a bad idea since (at least parts of) VS Code can create another `.vscode` directory inside it. IOW it might not always behave like a _normal_ `.vscode` subdirectory would.

**Comment by yeahg-dev** [comment]
Thank you for checks and side note! 

I don't know if I understood it well, Does Uno Platform Extension also provide task definition?

**Comment by agneszitte** [comment]
@spouliot what is the status of this issue lately, please?

**Comment by spouliot** [comment]
@agneszitte it's tracked as an enhancement in https://github.com/unoplatform/uno.vscode/issues/786 but it's not working on other extensions I tried, so there might be something broken inside VS Code itself.
