### ISSUE TITLE
"Invalid file name: It must contain only [^a-zA-Z0-9_.]+" when App Bundle enabled

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#1765]
## Current behavior
Debug build success. Release build fails with a few errors all saying:
"Invalid file name: It must contain only [^a-zA-Z0-9_.]+"

## Expected behavior
Build successfully.

## How to reproduce it (as minimally and precisely as possible)
In latest Uno app template published in Marketplace for VS 2019, for Android project enabled Android App Bundle generation with this line in .csproj:
`<AndroidPackageFormat>aab</AndroidPackageFormat>`

[unoApp6.zip](https://github.com/unoplatform/uno/files/3702451/unoApp6.zip)

## Environment

Nuget Package: Uno.UI 

Package Version(s): v1.45.0 and also the latest dev version 

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?
Similar issue
https://github.com/unoplatform/uno/issues/1364

**Comment by vincentcastagna** [comment]
This PR is supposed to fix this issue, isn't it  ? https://github.com/unoplatform/uno/pull/1616/files

**Comment by artemious7** [comment]
This line
`<AndroidUseAapt2>false</AndroidUseAapt2>`

should have fixed it, but the problem is still there. I checked, this line is present in project.
Also the strange thing is that it builds fine in Release mode in Azure Pipelines, but fails to build on my machine.

**Comment by MartinZikmund** [comment]
Try to close VS and then delete `bin` and `obj` folders in the project. Then rebuild and see if it helped

**Comment by artemious7** [comment]
That was the first thing I did. Moreover, it was a clean new project from template

**Comment by artemious7** [comment]
@MartinZikmund I also tried the same project on another machine with VS 2019, the same problem. Please, try it on your machine. I attached the repro project in the description.

![image](https://user-images.githubusercontent.com/16724889/66427812-6c186500-ea1d-11e9-9cdf-9a817ea1f086.png)

**Comment by MartinZikmund** [comment]
@artemious7  I am not at my dev PC right now, but please try to copy the `<AndroidUseAapt2>false</AndroidUseAapt2>` line to the release `PropertyGroup` in Android .csproj as well, like this:

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AndroidUseAapt2>false</AndroidUseAapt2>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    ...
```

**Comment by MartinZikmund** [comment]
You are right, even with `<AndroidUseAapt2>false</AndroidUseAapt2>` in Release configuration it seems it fails 😕 .

**Comment by MartinZikmund** [comment]
@ghuntley I am hitting this problem as well when I switch to Android App Bundle packaging instead of APK, is there a way around this?

**Comment by jeromelaban** [comment]
If you want to work around it, you can move the assets folder out of the shared project. Are you testing with a 16.4 VS preview build ?

**Comment by MartinZikmund** [comment]
Yes, preview build. For now, I have just reverted back to APKs for simplicity. 
Is this a VS issue? If, yes, I would upvote 😀

**Comment by jeromelaban** [comment]
It's a VS issue, it's been fixed just not yet published...

**Comment by YGuerin** [comment]
Seems to be fixed on latest VS 2019 (16.5.0)
![image](https://user-images.githubusercontent.com/11750340/77329943-10a11180-6cf5-11ea-9ea0-c1f5526f5aa3.png)

**Comment by jeromelaban** [comment]
The patch took a very long time to end in production :)

**Comment by jeromelaban** [comment]
This issue has been fixed, leaving the templates in https://github.com/unoplatform/uno/issues/1765 to be updated.

**Comment by Yahya0007** [comment]
I am still getting it n VS 2019 version 16.6.2. What can I do to fix it?

**Comment by jeromelaban** [comment]
@Yahya0007 Which version of Uno are you using ?
