### ISSUE TITLE
`InfoBar` severity icon alignment is incorrect

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#19286]
### Current behavior

Although the font glyphs seem to be aligned correctly, they still seem aligned incorrectly in a running application

### Works on UWP/WinUI

None

**Comment by morning4coffe-dev** [comment]
When looking at this more closely, all the icons seem misaligned. I will try to take a look what is happening there.

![Image](https://github.com/user-attachments/assets/fe80ba2b-6915-450b-9850-79997c548dc0)

**Comment by MartinZikmund** [comment]
This might have been fixed for Skia, worth verifying

**Comment by morning4coffe-dev** [comment]
I think it is still the same @MartinZikmund: 

<img width="1078" height="752" alt="Image" src="https://github.com/user-attachments/assets/07807fe0-4fbf-45ec-9dd1-1d739b823bb9" />

Tested on: "Uno.Sdk": "6.4.0-dev.19"
