### ISSUE TITLE
CalendarView styles are different from platform to platform

### ISSUE THREAD

**Issue by ADD-Noureddine-Maachi** [unoplatform/uno#19733]
### Current behavior

- The Desktop platform changes the language of the calendar view automatically, and adds the string '1e' between the month and the year.
- If the selected day is the today's button, the text color is the today's foreground.
- WinUI does not allow to set the selected background color.

### Expected behavior

- The Desktop platform does not change the language automatically and does not add the string '1e' between the month and the year.
- The selected day always changes the color to the defined foreground.
- WinUI allows to set the selected background color.

### How to reproduce it (as minimally and precisely as possible)

 1. Open the attached solution and compile it.
 2. Execute it in the desired head.
 3. Check the style of the calendar view.

### Workaround

- We have a workaround for the WinUI behaviour, changing the style as defined in the solution.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 5.6.45

### Affected platforms

Skia (WPF), WebAssembly, Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

17.13.3

### Anything else we need to know?

All behaviors work on WinUI except the last one.

**Comment by Jen-Uno** [comment]
@ADD-Noureddine-Maachi this issue should already be fixed; can you validate?

**Comment by ADD-Noureddine-Maachi** [comment]
@Jen-Uno I've tested the solution I attached changing the Uno.Sdk version to the 6.4.58 (the last stable one) and according to the points I mentioned in _Current Behavior_:
1. ❌ The '1e' still shows up when having the spanish culture.
2. ✅ Works correctly.
3. ❌ The `SelectedBackground` still does not work for WinUI.

**Comment by Jen-Uno** [comment]
@ADD-Noureddine-Maachi could you also test with the latest dev bits? [6.6.0-dev.36](https://www.nuget.org/packages/Uno.Sdk/6.6.0-dev.36)

**Comment by ADD-Noureddine-Maachi** [comment]
@Jen-Uno Tested in [6.6.0-dev.123](https://www.nuget.org/packages/Uno.Sdk/6.6.0-dev.123).
- ✅ The '1e' does not show up anymore when having the spanish culture.
- ❌ The `SelectedBackground` still does not work well. Also the properties `SelectedBorderBrush` and `SelectedForeground` are not working as expected platform to platform.

I noticed that @MartinZikmund has opened this issue #22709. I will subscribe to it also so I can track those changes too.

Thanks. 😁
