### ISSUE TITLE
[Skia] `SkiaRendered` library can't be refered by another

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/uno#20312]
### Current behavior

I have a core library which build with `SkiaRenderer` uno feature, and i get a error when building another project which refferenced it via nuget pack, even the project alse added the `SkiaRenderer` feature:
```text
The assembly C:\Users\19938\.nuget\packages\dy.ui.core\0.6.2\lib\net9.0-browserwasm1.0\Dy.UI.Core.dll has a different UnoUIRuntimeIdentifier than the one used to build the project. (Expected: skia, Actual: UnoUIRuntimeIdentifier)
```

### Works on UWP/WinUI

None

### Renderer

- [x] Skia
- [ ] Native

**Comment by jeromelaban** [comment]
Thanks. Can you provide a [repro sample](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs) that demonstrates the issue?

**Comment by SongOfYouth** [comment]
> Thanks. Can you provide a [repro sample](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs) that demonstrates the issue?

Please check https://github.com/SongOfYouth/SkiaRefDemo

**Comment by SongOfYouth** [comment]
any update for it?

**Comment by jeromelaban** [comment]
Thanks, so the error message is misleading, and the scenario should not fail, but if you're enabling `SkiaRenderer`, you generally should not need to have neither `browserwasm` nor `desktop`, as those are covered by `net9.0`.

We'll enhance the docs for this.

**Comment by SongOfYouth** [comment]
> Thanks, so the error message is misleading, and the scenario should not fail, but if you're enabling `SkiaRenderer`, you generally should not need to have neither `browserwasm` nor `desktop` in your library project, as those are covered by `net9.0`.
> 
> We'll enhance the docs for this.

You means there is no any platform special code when enabling `SkiaRenderer`?

**Comment by rajamatt** [comment]
This issue is fixed for SR3 with SDK version 6.0.119.

---

Tested with:
Templates/SDK: 6.0.119 (which uses Uno version 6.0.740)
Platform(s): Wasm, Desktop
IDE: VS 2022 - 17.14.4
VS VSIX: [6.0.48](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=167696&view=results)
OS: Windows

**Comment by ToddGlodek** [comment]
FYI : I updated to [SDK version 6.0.130](https://www.nuget.org/packages/Uno.Sdk/6.0.130), but I am still experiencing this issue when building **TargetFramework net9.0-browserwasm**:

> A reference to either Uno.WinUI.Runtime.WebAssembly or Uno.WinUI.WebAssembly has been detected. See more information at https://aka.platform.uno/UNOB0017

**Comment by jeromelaban** [comment]
@ToddGlodek you must be experiencing another issue. Please make sure to open another issue with a repro of your problem. Thanks!

**Comment by rizwaanbutt** [comment]
Hi @ToddGlodek,

Have you opened a new ticket for the issue you're getting? If so, please share the link here; it might be that I can help.

Kind Regards
