### ISSUE TITLE
[UNO 6] Icons not showing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#20432]
### Discussed in https://github.com/unoplatform/uno/discussions/20428

<div type='discussions-op-text'>

<sup>Originally posted by **AuderixDev** May 16, 2025</sup>
Are there any know issues with Uno 6.0.67 and BitmapIcons or ImageIcons not showing?

Missing BitmapIcon in Uno Gallery:

![image](https://github.com/user-attachments/assets/ddae225a-ac65-4bfe-802f-91b8d696e029)

In my Code I have a more complex process. Build process adds SVGs to `/Assets/Icons/Generated/...`. Resizetizer makes PNGs from this SVGs.
A custom class inherits from ImageIcon and setting the Source with the PNGs (`Source = new BitmapImage(new Uri($"{AssetFolderPath}{generatedIconName}"));`) 

But the Result is the same. ImageIcon is not showing in Web (WinAppSdk still works)
This worked before with Uno 5.6.51.</div>

**Comment by AuderixDev** [comment]
@jeromelaban 
Just did some simple Tests: 
Does not work: `<ImageIcon Source="ms-appx:///Assets/Icons/icon_folder.png" />`
This works: `<BitmapIcon UriSource="ms-appx:///Assets/Icons/icon_folder.png" />`

Setting the Source from Code-Behind on ImageIcon does also not work
Source = new BitmapImage(new Uri("ms-appx:///Assets/Icons/icon_folder.png"))

**Comment by morning4coffe-dev** [comment]
CC @MartinZikmund, I think you've been already looking into this one with unexpectedapis?

**Comment by MartinZikmund** [comment]
Yes, this should now be fixed by https://github.com/unoplatform/uno/pull/20409 , new version of Gallery will need to be pushed, but it should already be working in canaries.

**Comment by AuderixDev** [comment]
@MartinZikmund, @morning4coffe-dev 
No, the issue is still not resolved. (tested with 6.0.96 and 6.1.0-dev.145)

In our project, images/ImageIcons are still not being displayed.
I was now able to reproduce the issue in a newly created project!

We're still using net8.0 because net9.0 doesn't support multithreading .
In the .csproj, we have `<WasmShellEnableThreads>true</WasmShellEnableThreads>` and `<WasmShellPThreadsPoolSize>8</WasmShellPThreadsPoolSize>`.
As a result, the icons are no longer loaded. This is a big downgrade bug introduced with uno version 6!

When I also enable the SkiaRenderer, the WASM crashes after the loading bar reaches 100%.
So it is not possible for our company to upgrade to uno 6.0...

**Comment by jeromelaban** [comment]
Thanks. This issue was specifically for Skia rendering, not native rendering. If you can provide a repro for this in a separate, it might help direct the issue differently.

Note that the SkiaRendering is not supported on net8.

**Comment by AuderixDev** [comment]
@jeromelaban ah i didn't know, that SkiaRendering is not supported on net8. thanks for clarification.

I pushed my Testproject here: https://github.com/AuderixDev/UnoApp19
With net8 + native rendering + uno 6 + Threading.

this is the result:

![Image](https://github.com/user-attachments/assets/b27c913e-19f4-41b3-bc94-9cd41873f989)
```xaml
  <StackPanel Orientation="Vertical"
                            HorizontalAlignment="Center">

                    <TextBlock Text="Image " Margin="0,10,0,0"/>
                    <Border Background="Gray" Height="48" Width="48">
                        <Image Source="ms-appx:///Assets/Icons/icon_home.png" />
                    </Border>

                    <TextBlock Text="ImageIcon "
                               Margin="0,10,0,0" />
                    <Border Background="Gray"
                            Height="48"
                            Width="48">
                        <ImageIcon Source="ms-appx:///Assets/Icons/icon_home.png" />
                    </Border>

                    <TextBlock Text="BitmapIcon"
                               Margin="0,10,0,0" />
                    <Border Background="Gray"
                            Height="48"
                            Width="48">
                        <BitmapIcon UriSource="ms-appx:///Assets/Icons/icon_home.png" />
                    </Border>
                </StackPanel>
```

**Comment by jeromelaban** [comment]
Thanks, please open an issue with a [complete repro](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs), so we're talking about the same behavior.

**Comment by jhanvi03** [comment]
Issue resolved with latest sdk. 

<img width="1345" alt="Image" src="https://github.com/user-attachments/assets/834fc3d5-ee09-461c-8fd8-0c94a509653b" />
