### ISSUE TITLE
[WASM Skia] Odd/incorrect ViewBox sizing/font rendering

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#20828]
### Current behavior 🐛

How it looks with skia rendering (notice the rating number font stretching oddly and last star outline getting clipped):

![Image](https://github.com/user-attachments/assets/e5477e27-989e-4965-a14e-6c9a19825e17)

This only appears to be an issue on WASM - it renders correctly on other platforms.

### Expected behavior 🎯

How it should look (and how it looks on non-WASM Skia and WASM native):

![Image](https://github.com/user-attachments/assets/a5328f87-e371-4659-be90-11f08f9de3e1)

### How to reproduce it (as minimally and precisely as possible) 🔬

Minimal repro project: [UnoTest.zip](https://github.com/user-attachments/files/20822606/UnoTest.zip)

### Workaround 🛠️

None

### Renderer 🎨

- [x] Skia
- [ ] Native

### Affected platforms 📱💻🖥️

WebAssembly

### Uno.Sdk version (and other relevant versions) 📦

6.0.x, 6.3.28, 6.4.0-dev.65

**Comment by MartinZikmund** [comment]
The `RatingControl` clipping may have been fixed in recent releases, but not sure about the text scaling. We may want to validate after the new text rendering engine is merged

**Comment by mikernet** [comment]
Note: this is a custom control, not the WinUI `RatingControl`.

**Comment by mikernet** [comment]
The result on Uno.SDK version `6.3.28` and `6.4.0-dev.65` is still the same.
