### ISSUE TITLE
[ListView] Dragging / Reordering items lead to wrong visible list

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#20993]
### Current behavior 🐛

Dragging items outside Listview area, when reorder and drag is enabled, causes a wrong visible list at screen.
Note that the items are still there and they come back, depending on the movement you do.

![Image](https://github.com/user-attachments/assets/13ca0f42-f0d4-4c38-af62-82ac4d8849e3)

### Expected behavior 🎯

Should work as expected.

### How to reproduce it (as minimally and precisely as possible) 🔬

On this snippet, try to drag one of the items outside the listview.
If you go up and down the item will disappear for a while. If you let it back it will appear again.

https://playground.platform.uno/#445388a1

### Renderer 🎨

- [ ] Skia
- [ ] Native

**Comment by jhanvi03** [comment]
The issue still persist in latest Playground canary. 

Tested with: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=172456&view=results

https://github.com/user-attachments/assets/c8214c74-12e1-44bd-a063-3cb2bfa6da2a

**Comment by nickrandolph** [comment]
@Xiaoy312 can you confirm this is fixed?

**Comment by Xiaoy312** [comment]
the issue is fixed on wasm & desktop WITH SKIA_RENDERER.
the [playground canary](https://playgroundcanary.z19.web.core.windows.net/#445388a1) is still using native renderer, I don't think it is worth considering for now.

sample: [u20993_new.zip](https://github.com/user-attachments/files/21605127/u20993_new.zip)
proof: // recorded on wasm w/chrome
![Image](https://github.com/user-attachments/assets/1c99a6c6-19d8-443b-91a7-b7c67228b746)

**Comment by GabrielLaban** [comment]
The issue still persist in latest Playground canary.

Tested with: https://playgroundcanary.z19.web.core.windows.net/#listview

https://github.com/user-attachments/assets/8909fd9d-8b96-4bb4-82e3-6b8e871d2efc

**Comment by Xiaoy312** [comment]
> the [playground canary](https://playgroundcanary.z19.web.core.windows.net/#445388a1) is still using native renderer, I don't think it is worth considering for now.

edit: you can use the sample in my last comment with wasm, it should be fixed there.

**Comment by GabrielLaban** [comment]
Fixed with latest stable SDK version 6.2.25.
Tested with:
Templates/SDK: 6.2.25
Platform(s): Desktop, Wasm
VS VSIX: [6.2.5]
IDE: VS 2022 - 17.14.12
OS: Windows
