### ISSUE TITLE
Cannot initialize window as maximized

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#21435]
### Discussed in https://github.com/unoplatform/uno/discussions/21339

<div type='discussions-op-text'>

<sup>Originally posted by **Tad29Eng** August 22, 2025</sup>
I create desktop app, how to startup main app window in maximize size (same as pressing maximize button in window) 
</div>

I try use in App.xaml.cs

```csharp
 var presenter = (OverlappedPresenter)MainWindow.AppWindow.Presenter;
 presenter.Maximize();
```

but this not worked, when app runing exception thrown: System.NullReferenceException Microsoft.UI.Windowing.OverlappedPresenter.Maximize()

**Comment by MartinZikmund** [comment]
This seems to be happening even after initialization, so this might be a deeper issue

**Comment by dgalo9** [comment]
Having the same issue, I'll appreciate any update. 

<img width="907" height="618" alt="Image" src="https://github.com/user-attachments/assets/45c4e91c-a31c-4d58-a7c2-de86cfd0806e" />

**Comment by LewisIsWorking** [comment]
I have the same issue. 
The closest I've been able to achieve is setting the window to use the monitor's max size, which leaves things looking strange.

**Comment by dgalo9** [comment]
@MartinZikmund any response here?? Is almost impossible to get the Host available on any part of the code. I know you should have many important things to do but this is mandatory, is making us considering to leave Uno because errors like this and not having immediate solution or not even a response is a clear red flag.

**Comment by MartinZikmund** [comment]
Unfortunately, I was focused on various client issues, which meant I wasn't able to completely fix this issue yet. That being said, it will be on my list tomorrow/beginning next week.

**Comment by dgalo9** [comment]
Thank you. I understand that paying customers are more important, and I appreciate your time. I'll continue to look for a solution so we can continue our project. @MartinZikmund

**Comment by dgalo9** [comment]
Hi @MartinZikmund This issue appears to be fixed from your side. Could you please tell me how can I apply the fix to my project?? Thanks.

**Comment by MartinZikmund** [comment]
@dgalo9 it will be included in the latest Uno.Sdk dev packages very soon (maybe today even)

**Comment by dgalo9** [comment]
@MartinZikmund thanks a lot.

**Comment by rajamatt** [comment]
Looks fixed with latest dev sdk 6.4.0-dev.34 that was released today, no more error.

---

Tested with:
Templates/SDK: 6.4.0-dev.34 (which uses Uno version 6.4.0-dev.187)
Platform(s): Desktop
IDE: VS 2022 - 17.14.16
OS: Windows

**Comment by dgalo9** [comment]
Hi @rajamatt is this possible for you to show your implemented code?? I'm using the last Uno.SDK version (6.3.28) but the error still remains for me. Thanks in advance.

**Comment by rajamatt** [comment]
Hi @dgalo9! Since the fix in #21497 wasn't backported, the error will still be present on all Uno.Sdk 6.3 versions.

The error should be gone with the latest dev 6.4 versions (such as [6.4.0-dev.34](https://www.nuget.org/packages/Uno.Sdk/6.4.0-dev.34)). Once we release a stable version for 6.4 you will be able to use that stable version as well. For my tests I was using the code from the issue description.

**Comment by dgalo9** [comment]
Thanks @rajamatt for taking the time to clarify this. Best regards.
