### ISSUE TITLE
`WebView2` Unable to load local content

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#21601]
### Current behavior 🐛

According to the docs you should be able to place a html file in a folder and then navigate to it in the webview2 (see https://platform.uno/docs/articles/controls/WebView.html#navigating-to-web-content-in-the-application-package)
This doesn't appear to work and yields an error in the WebView2:

<img width="1516" height="950" alt="Image" src="https://github.com/user-attachments/assets/cfdef6f1-3261-457e-a069-c75a5a3d43b6" />

Also a bunch of console warnings:
```
warn: Uno.UI.Xaml.Controls.IWebView[0]
      This WebView control instance does not have a native WebView child, the control template may be missing.
fail: System.Type[0]
      DeleteObject failed: The operation completed successfully.

fail: System.Type[0]
      DeleteObject failed: The operation completed successfully.

fail: System.Type[0]
      DeleteObject failed: The operation completed successfully.

fail: System.Type[0]
      DeleteObject failed: The operation completed successfully.

fail: System.Type[0]
      DeleteObject failed: The operation completed successfully.
```

### Expected behavior 🎯

No warnings in console and content should be displayed

### How to reproduce it (as minimally and precisely as possible) 🔬

[UnoApp34.zip](https://github.com/user-attachments/files/22868758/UnoApp34.zip)

### Renderer 🎨

- [x] Skia
- [ ] Native

### Affected platforms 📱💻🖥️

Desktop (Windows)

### Uno.Sdk version (and other relevant versions) 📦

6.3.28

### TODO

- [x] Fix WebView2 inicialization #21626 
- [x] Enable Runtime test #21682

**Comment by nickrandolph** [comment]
Note that this works as expected with the WinAppSdk target

**Comment by DevTKSS** [comment]
@nickrandolph hey, that first logged line I have too always in my UnoWebView2App 🤔 but I don't call local content for this. Do you have any information about the issue source to estimate for this?

The website in my app (the HP of Uno) does load and is initial set via Mvux `State<Uri>`
🤔 But I am not sure if the initial showup look of it is correct like that. The headline does look odd 😅 wrong formatted maybe? But I can not tell if this is caused by the WebView2 or the website itself 👀

You can find the details about this on [my past discord message on the uno server here](https://discord.com/channels/1182775715242967050/1182775715729526908/1424783255877713940)
@MartinZikmund could someone check if that strange display needs an issue for WebView2 or if its just the homepage?

**Comment by morning4coffe-dev** [comment]
A similar issue is actually happening on Wasm as well, there the right local url mapping doesn't seem to work correctly as opposed to the WebView2 not being inicialized in time.

**Comment by morning4coffe-dev** [comment]
Done via: https://github.com/unoplatform/uno/pull/21626

**Comment by agneszitte** [comment]
This issue can now be retested, starting with **Uno.Sdk version [6.4.0-dev.50](https://www.nuget.org/packages/Uno.Sdk/6.4.0-dev.50)** or newer.

**Comment by khaskoul** [comment]
The issue seems to be partially fixed. See results per Target:

**Desktop:** (Text and background are both black, text can be seen by highlighting it)
<img width="995" height="557" alt="Image" src="https://github.com/user-attachments/assets/8434b98b-0ce2-4e9f-8ea2-55af0c75dbcd" />



**Wasm:** (Server IP address could not be found)
<img width="1036" height="641" alt="Image" src="https://github.com/user-attachments/assets/df633a7d-2b96-4c86-bbba-42f42e8db7a5" />



**WinAppSDK:** (Behaves as expected)
<img width="851" height="423" alt="Image" src="https://github.com/user-attachments/assets/4b01a00e-68b2-4173-a2ef-142c7e99a359" />



Tested using latest SDK version 6.4.0-dev.79
Tested with:
Templates/SDK: 6.4.0-dev.79
Platform(s): Desktop, WASM
VS VSIX: 6.4.0-dev.42
VS Code: 0.23.0-dev.34
Rider
IDE: VS Code 1.105.1, VS 17.14.16, Rider
OS: Windows

**Comment by morning4coffe-dev** [comment]
@khaskoul Thanks! That is for now a proper behavior, Wasm is #21685, #21651.

**Comment by agneszitte** [comment]
@khaskoul this issue can now be retested, starting with Uno.Sdk **[6.4.0-dev.85](https://www.nuget.org/packages/Uno.Sdk/6.4.0-dev.85)** or newer.

**Comment by khaskoul** [comment]
The fix has been verified on Desktop

<img width="661" height="336" alt="Image" src="https://github.com/user-attachments/assets/c63bb3b4-aa67-43f5-9476-51b04dbb468f" />

Tested using latest SDK version 6.4.0-dev.85
Tested with:
Templates/SDK: 6.4.0-dev.85
Platform(s): Desktop, WASM
VS VSIX: 6.4.0-dev.42
VS Code: 0.23.0-dev.34
Rider
IDE: VS 17.14.19
OS: Windows
