### ISSUE TITLE
[Android] crash on Native randerer

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#21910]
### Current behavior 🐛

Mac: Build succeeds and solution deploys to emulator, but opening the app shows "unoApp keeps stopping".

Windows: Deployment shows "VM NotSuspendedException" error.
<img width="417" height="449" alt="Image" src="https://github.com/user-attachments/assets/655a5a63-a27f-464f-be84-0fb6a3bb45e2" />

Both .NET 9 and .NET 10 (native projects): Issue occurs.

Khalil’s side: No exception occurs, but the app still keeps stopping after launch.

Logs:

[Mac-Rider-BuildLogs.txt](https://github.com/user-attachments/files/23660106/Mac-Rider-BuildLogs.txt)
[mac-Rider-VerboseLevelLogs.txt](https://github.com/user-attachments/files/23660105/mac-Rider-VerboseLevelLogs.txt)

[Windows-BuildLogs.txt](https://github.com/user-attachments/files/23660396/Windows-BuildLogs.txt)

 Note: The issue is not reproducible with 6.3.28 version. it is a regression in 6.4

### Expected behavior 🎯

should not crash

### How to reproduce it (as minimally and precisely as possible) 🔬

1. Create a Blank/recommended project with .NET 9 or .NET 10 framework and with Native
2. Build solution for Android TFM
3. Observe the crash

### Renderer 🎨

- [ ] Skia
- [x] Native

### Affected platforms 📱💻🖥️

Android

### Uno.Sdk version (and other relevant versions) 📦

SDK/Template: 6.4.26, 6.5.0-dev.39

### IDE version 🧑‍💻

VS, VSC, Rider

**Comment by MartinZikmund** [comment]
The dialog itself is a intermittent VS issue. The fact that the app stops needs to be investigated though.

**Comment by jeromelaban** [comment]
Likely already fixed by an upcoming HD build

**Comment by Jen-Uno** [comment]
@jhanvi03

**Comment by jhanvi03** [comment]
@Jen-Uno @jeromelaban, issue still persist with latest sdk/template 6.4.28.

Tested with:
Windows: 
IDE: VS
VSIX: 6.4.15

Mac:
IDE: Rider, VSCode
Plugin/VSIX: 1.8.19, 0.23.6

**Comment by jeromelaban** [comment]
Will be fixed in the next RC.

**Comment by kazo0** [comment]
@jhanvi03 is this now working?

**Comment by jhanvi03** [comment]
@kazo0, Issue still persist with sdk/template 6.4.31 & 6.5.0-dev.39

**Comment by kazo0** [comment]
Fyi @jeromelaban maybe I missed a backport? Or was SR6 the release that would include this?

**Comment by jeromelaban** [comment]
It's in the 0.8 version of aigen, it's not included yet, https://github.com/unoplatform/uno.hotdesign/pull/5633 will do it.

**Comment by kazo0** [comment]
@jhanvi03 should be good to test again :)

**Comment by jhanvi03** [comment]
@kazo0, the issue still persist with Native renderer sdk/template 6.4.33

Tested with:
Sdk/template: 6.4.33
OS: Mac
IDE: Rider
Framework: .NET 9, .NET 10

**Comment by kazo0** [comment]
@jhanvi03 can you retry with the 6.4.37 sdk?

**Comment by jhanvi03** [comment]
@kazo0, the issue still persist with Native renderer sdk/template 6.4.37 

Tested with:
Sdk/template: 6.4.37
OS: Mac
IDE: Rider 2025.3.0.3
Framework: .NET 9, .NET 10

**Comment by jhanvi03** [comment]
Issue still persist with sdk/template 6.4.40

[Window VS.txt](https://github.com/user-attachments/files/23866124/Window.VS.txt)
[Rider-mac-Android.txt](https://github.com/user-attachments/files/23866123/Rider-mac-Android.txt)

**Comment by agneszitte** [comment]
@jeromelaban mentioned that the fixes done for https://github.com/unoplatform/uno/issues/21881 will also fix this issue, so I am closing it so they can both be reviewed at the same time.

**Comment by jhanvi03** [comment]
Issue Resolved with Latest sdk/template 6.4.42. Solution is getting deployed on emulator with Native project

Tested with:
SDK/template: 6.4.42
IDE: Rider on both Mac + Windows and VS
Framework: .NET10, .NET9


<details><summary>Snapshot</summary>
<p>
Windows: Rider
<img width="1818" height="929" alt="Image" src="https://github.com/user-attachments/assets/898604d6-b032-453d-9991-17e43d0acf9d" />

Windows: VS

<img width="1808" height="847" alt="Image" src="https://github.com/user-attachments/assets/7cfb96a9-8add-49d0-8891-50ed4fbd325b" />

Mac: Rider
<img width="1431" height="854" alt="Image" src="https://github.com/user-attachments/assets/35ca6897-12f5-459f-b3a3-adeccb8fb079" />



</p>
</details>
