### ISSUE TITLE
[WASM] LocalSettings does not persist data across sessions

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2923]
## Current behavior

Values set in ApplicationData.Current.LocalSettings.Vaclues are not persisted across page reloads

## Expected behavior

Data should be persisted

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP once, observe that no time was loaded.  Restart the application and note that the time of previous launch is now displayed.  Launch in WASM and observe that, regardless of how many times you reload the page or close/open browser windows to the page it never has a time from a previous session.  Tested in Firefox and Chrome.

[App37.zip](https://github.com/unoplatform/uno/files/4428810/App37.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.2.0-dev.374
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This has been fixed in 1.2 and later bootstrapper builds.

**Comment by peternary** [comment]
I updated the attached test project to all latest Uno packages and it is still not working for me.  Is any further configuration required?

**Comment by jeromelaban** [comment]
This could be related to the synchronization of the emscripten filesystem. The current implementation was naively based on normal files, but for this API, this looks like it is not appropriate. We'll be adjusting it.

**Comment by peternary** [comment]
Confirmed fixed in latest

**Comment by Stannieman** [comment]
Will this only come to version 3 or also in some future 2.x patch?
And when can we expect the NuGet packages (either of the 2) to be updated?

**Comment by jeromelaban** [comment]
This fix can be backported to 2.4, we'll do that. It should be available in a service update soon.

**Comment by Stannieman** [comment]
@jeromelaban thank you sir! Much love!
