### ISSUE TITLE
[WASM] IsTextSelectionEnabled not functioning for TextBlock

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3446]
## Current behavior

If a TextBlock has IsTextSelectionEnabled set to true then text is still not selectable.

## Expected behavior

Text should be selectable, as in UWP

## How to reproduce it (as minimally and precisely as possible)

At the sample [here](https://playground.platform.uno/#e59921c0) you cannot select text, even though the appropriate property is set.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.636
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by peternary** [comment]
Confirmed fixed in latest

**Comment by DierkDroth** [comment]
@jeromelaban I still get a UNO0001 'not implemented' warning  on WASM with latest dev pieces. 

Is that expected?
