### ISSUE TITLE
Empty XAML Designer when openning MainPage.xaml

### ISSUE THREAD

**Issue by constantdupuis** [unoplatform/uno#4616]
## Current behavior

When I click on the MainPage.xaml file, an empty window open.  No way to edit XAML file neither in XML or deisnger mode.
See bellow :
![2020-11-26 10_27_27-Window](https://user-images.githubusercontent.com/31339604/100332754-0d6fcb00-2fd2-11eb-8d95-e13141c01b38.png)

I build WPF and Xamarin projets, and they both show the XAML editors (text and design). So the issue look to be limited to UNO project.

## Expected behavior

When you click on the MainPage.xaml, the split XAML Designer should show.

## How to reproduce it (as minimally and precisely as possible)

Provided bellow the project.
[App1.zip](https://github.com/unoplatform/uno/files/5601867/App1.zip)

## Workaround

I had to open MainPage.xaml.cs and select App1.UWP in the top left dropdown.

See joined screen capture.
![2020-11-26 11_43_22-App1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/31339604/100341267-a0156780-2fdc-11eb-9174-1eae7d018bc8.png)

## Environment

Nuget Package:

- [x ] Uno.UI 3.3.0/ Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] UNO.Core 2.0.0

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version:16.8.2 )
- [x ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thank you for the report, this is a known Visual Studio issue, listed in the [wizard page here](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-wizard.md#the-xaml-editor-may-be-empty). Could you upvote these ([Link 1](https://developercommunity.visualstudio.com/content/problem/1267071/trying-to-open-xaml-files-shows-empty-path-name-is.html), [Link 2](https://developercommunity.visualstudio.com/content/problem/1266894/uwp-xaml-intellisense-fails-when-using-shared-proj.html)) VS community issues to help get the issue fixed ?

**Comment by constantdupuis** [comment]
Thank's, for quick response, how can I up vote ?
Sorry I'm noob, I logged into developer-community, then I leave a message ?



Le jeu. 26 nov. 2020 à 14:52, Jérôme Laban <notifications@github.com> a
écrit :

**Comment by jeromelaban** [comment]
No worries! Once logged in, on the side you have an up arrow on both issues: 
![image](https://user-images.githubusercontent.com/5839577/100363372-a13d9900-2fca-11eb-82a0-05d47a7ed1fe.png)

**Comment by constantdupuis** [comment]
Done, I'll close the issue.

Thank's

Le jeu. 26 nov. 2020 à 15:35, Jérôme Laban <notifications@github.com> a
écrit :

**Comment by GW-FUB** [comment]
@constantdupuis Could you put this fix in the FAQ as this is still not fixed. I had to search through the closed issues to find a solution to this (important) problem.

**Comment by constantdupuis** [comment]
Sure I can add the fix in the FAQ, how can I do that ?
I guess I need to create a pull request on the doc ?

**Comment by GW-FUB** [comment]
@jeromelaban I also don't know how to do this. Can you help?
