### ISSUE TITLE
NavigationView: Dynamically adding items when PaneDisplayMode=Top displays incorrectly on wasm

### ISSUE THREAD

**Issue by capdj** [unoplatform/uno#4848]
## Current behavior

Given the following XAML:

```
        <NavigationView PaneDisplayMode="Top" x:Name="nvMain">
            <NavigationView.MenuItems>
                <NavigationViewItem Content="Hello" />
            </NavigationView.MenuItems>
        </NavigationView>
```

...then if you add another item at runtime, e.g. simply doing

```
            nvMain.MenuItems.Add(new NavigationViewItem { Content = "Another" });
```

...this new item will display correctly on UWP, but on WASM the new item isn't rendered - the user can't see or click on it.

This only seems to happen with PaneDisplayMode=Top, it works as expected otherwise.

## Expected behavior

Dynamically added items will appear on WASM in the same way as they do on UWP.

## How to reproduce it (as minimally and precisely as possible)

See above XAML and code - dropping this into a new Uno project should exhibit the bug.

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

3.3, 3.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

Can you try with `Microsoft.UI.Xaml.Controls.NavigationView` instead? If you don't specify any namespace, it'll use `Windows.UI.Xaml.Controls.NavigationView` which is a now older version of that control.

**Comment by capdj** [comment]
Behaviour is better but still not perfect using Microsoft.UI.Xaml.Controls.NavigationView - the items added at runtime do appear then, but (unlike the items specified in the XAML) don't get the blue underline when clicked - a much less significant problem, but could still be improved.

**Comment by jeromelaban** [comment]
Thanks for the update. @MartinZikmund is this something you fixed in your recent PRs ?

**Comment by MartinZikmund** [comment]
Yes, I think the PR merged today should fix that.  Can you please try downloading the latest preview package of Uno.UI (about 4 hours old :-) ) and check if it works in that version?

**Comment by capdj** [comment]
If I install the latest preview packages, then the behaviour looks fine with Microsoft.UI.Xaml.Controls; thanks!

The Windows.UI.Xaml.Controls version is still broken, however I guess this can be closed if the intention is that we should be using Microsoft.UI.Xaml.Controls moving forwards (?) - I'm only using Windows.UI.Xaml.Controls as that's what the template gave me.

**Comment by MartinZikmund** [comment]
We still want to have the feature parity, so we will do bug fixes on the "old" control, but the new one will get WinUI parity going forward, so it is preferable to use it instead 👍

**Comment by francoistanguay** [comment]
Moving on with MUX
