### ISSUE TITLE
[Gallery][WASM/iOS]ListView item is not highlighted when the tab is clicked.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#4906]
How to reproduce it 

1. Open the link https://unogallerycanary.z27.web.core.windows.net/
2. Click on any control tab for component or feature ( for example “card” tab)
3. Observe the “Card” tab is not highlighted in purple color.

**Current behavior**
Controls tab is not highlighted in purple color when the tab is clicked.

**Expected behavior**
Controls tab should highlight in purple color when the tab is clicked.

**Attachment:**
**Actual Result:**
![error screen1](https://user-images.githubusercontent.com/74563602/104518635-fb6bdb00-55c5-11eb-96ec-183f374fdf19.png)

**Expected Result:**
![correct screenshot](https://user-images.githubusercontent.com/74563602/104518689-176f7c80-55c6-11eb-904f-70e004684a29.png)

**Environment**

Nuget Package:

Package Version(s):
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=23486&view=results

Affected platform(s):

 Windows

**Comment by davidjohnoliver** [comment]
Seems like the same issue as https://github.com/unoplatform/uno/issues/4786

**Comment by dr1rrb** [comment]
@sakshi173 are you still able to reproduce it ? I see the selected state on my side with FF and Edge.

**Comment by sakshi173** [comment]
@dr1rrb Now issue is resolved and its working fine. Below is the screenshot.



![Listview highlight issue](https://user-images.githubusercontent.com/74563602/105375748-fa930480-5bd6-11eb-97ba-3ed0319b6c6b.png)

**Comment by sakshi173** [comment]
**Verified, Issue is Fixed -- Closing.**

Below is the screenshot.

![listview highlight](https://user-images.githubusercontent.com/74563602/105753104-2cc59e80-5f16-11eb-9efe-f8c4ceb1bbb3.png)

**Comment by sakshi173** [comment]
Same issue is having with iOS, due to that reopening the bug.

**Comment by jeromelaban** [comment]
Can you retry with the latest that I just pushed ?

**Comment by sakshi173** [comment]
@jeromelaban, I Retried with the latest build and the issue is still present.

**Comment by Xiaoy312** [comment]
\# 'Cards' navigation item
both mouseover and onclick effects are ok
mouseover/onclick effects tends to stuck on it always after first navigation into that page
____^ with or without debugger attached
____^ 100% repro OR "high chance" to repro..?
note: there are 3 effects here:
__mouseover: 12% purple background
__onlick: 12% purple background + ripple adding another 12% purple
__selected: 100% purple `|` bar on the left as selection indicator
the issue is the 12% purple background getting stuck, and wont go away
even if mouseover'd again and mouseleave'd

this is only seen on iOS, wasm is fine
\--
the cards page has always been pretty VERY heavy, despite what seems like just a few pretty simple cards...
showing only the first 1-4 cards doesnt get the mouseover/onclick effects to be stuck
starting from 5 cards, we can start to observe the issue
just showing the 5th card, no problem, so it isnt with any card in particular, but as a whole
\---
with a textblock and an extra setter on each VisualState: //checkbox is currently being pressed
![image](https://user-images.githubusercontent.com/2359550/107072456-27890f00-67b4-11eb-99dc-66665a7e3906.png)
this indicates the VisualState is reset correctly, whether with or without setter on "Normal" VisualState
~~not sure if the heavy-load of the page is messing up the dp precedence?~~

the stuck background is from the ripple
    ^ this is easily noticeable when a different RBG channel to mouseover,pressed,ripple effects

**Comment by Xiaoy312** [comment]
Closing this for #449

**Comment by sakshi173** [comment]
Verified, Issue is Fixed -- Closing
![buger list highlight](https://user-images.githubusercontent.com/74563602/107135898-9bb6d600-68cc-11eb-93e7-3c6da78331ac.png)
