### ISSUE TITLE
[Skia][Gtk] Number Keypad Enter key is not mapped properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5000]
## Current behavior

https://github.com/unoplatform/calculator/issues/347

## How to reproduce it (as minimally and precisely as possible)

Use the calculator on Linux snap

## Workaround

Use the other enter key.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
![](https://media.giphy.com/media/L0kbyQRamg30EzSXfS/giphy.gif)

**Comment by ZCostello** [comment]
Hi has anyone taken this on yet? I may have a go if not...

**Comment by jeromelaban** [comment]
@ZCostello You're welcome to take a look! We've not gotten to this yet, but it's likely to be an incorrect mapping at that location:

https://github.com/unoplatform/uno/blob/14293b7019001df5b1bdeef51c83a8690947c37d/src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkCoreWindowExtension.Keyboard.cs#L107

**Comment by ZCostello** [comment]
I have 10 build errors using Gitpod (before making any changes), so I'll have to see what I can do about about that...

However, I suspect it may be as simple as adding `GDK_KP_Enter => VirtualKey.Enter` to _uno/src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkCoreWindowExtension.Keyboard.cs_ (perhaps at line 230 underneath the Numpad mappings), as I'm not sure the Numpad Enter key was mapped at all; thanks for the heads-up with the link!

**Comment by jeromelaban** [comment]
Thanks for the update. Indeed `GitPod` should be working but for some reason build errors are not reported properly, we'll make some adjustments for that.

**Comment by duke7553** [comment]
@ZCostello Are you still able to reproduce this one? I tested on the latest Skia GTK from within WSL and it seems like the enter key on my keyboard's number pad is detected as `Gdk.Key.Return` which maps to `VirtualKey.Enter`.

If someone else can repro this bug, I'll open a PR which maps `Gdk.Key.KP_Enter` to `VirtualKey.Enter`.

**Comment by duke7553** [comment]
Never mind. It appears this still isn't working when testing in a VM
