### ISSUE TITLE
Fonts are not working on maccatalyst

### ISSUE THREAD

**Issue by edoust** [unoplatform/uno#8566]
### Current behavior

Create a new uno app using `dotnet new unoapp-winui-net6` then build and run the `maccatalyst` target

No font icons are displayed when building for `arm64`, when building for `x64` the app crashes on startup with this exception:

````c#
Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[String](IEnumerable`1 source)
   at Windows.UI.UIFontHelper.GetFontFromFamilyName(NFloat size, String familyName)
   at Windows.UI.UIFontHelper.GetCustomFont(NFloat size, String fontPath, FontWeight fontWeight, FontStyle fontStyle)
   at Windows.UI.UIFontHelper.InternalTryGetFont(NFloat size, FontWeight fontWeight, FontStyle fontStyle, FontFamily requestedFamily, Nullable`1 basePreferredSize)
   at Uno.Extensions.FuncMemoizeExtensions.<>c__DisplayClass8_0`6[[System.Runtime.InteropServices.NFloat, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Windows.UI.Text.FontWeight, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Windows.UI.Text.FontStyle, Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Microsoft.UI.Xaml.Media.FontFamily, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[System.Nullable`1[[System.Runtime.InteropServices.NFloat, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[UIKit.UIFont, Microsoft.MacCatalyst, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].<AsMemoized>b__0(NFloat arg1, FontWeight arg2, FontStyle arg3, FontFamily arg4, Nullable`1 arg5)
   at Windows.UI.UIFontHelper.TryGetFont(NFloat size, FontWeight fontWeight, FontStyle fontStyle, FontFamily requestedFamily, Nullable`1 preferredBodyFontSize)
   at Microsoft.UI.Xaml.Controls.TextBlock.GetAttributes()
   at Microsoft.UI.Xaml.Controls.TextBlock.GetAttributedText()
   at Microsoft.UI.Xaml.Controls.TextBlock.UpdateTypography()
   at Microsoft.UI.Xaml.Controls.TextBlock.MeasureOverride(Size size)
   at Microsoft.UI.Xaml.FrameworkElement.FrameworkElementLayouter.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.Controls.Layouter.Measure(Size availableSize)
   at Microsoft.UI.Xaml.LayouterElementExtensions.DoMeasure(ILayouterElement element, Size availableSize, Size& measuredSizeLogical)

````

Also including custom fonts in the `MacCatalyst/Resources/Fonts` folder is not working, build action is set to `BundleResource` - is that the right way to include fonts?

### Expected behavior

The icons should display correctly and the app should not crash

### Works on UWP/WinUI

Yes

### NuGet package version(s)

4.1.9

**Comment by jeromelaban** [comment]
This issue is likely fixed in Uno 4.2-dev builds. Can you try with this version? Note that you'll need to upgrade to the latest builds of multiple pieces: https://github.com/unoplatform/uno/discussions/7833

**Comment by edoust** [comment]
Yes this issue is still valid on `4.2.0-dev.673` and `maccatalyst15.4`

The main blockers on catalyst at the moment are IMO 
- the custom fonts not rendering at all,
- translations are not loading from the `resw` files (they do on windows, both `x:UId` and loading manually fails), and
- the wrong layout in the OS X windows (title bar hides part of the content, and the content is stretching to be larger than the window, so parts of the content is missing on the right and bottom)

If I can test something else to get closer to those issue please let me know and I will share the results

**Comment by jeromelaban** [comment]
The fonts and translations are supposed to be fixed by #8554. Maybe there's something else that is not working in your scenario, as for the layout for OS X this is likely a different issue. Can you open another issue with a screenshot?

**Comment by edoust** [comment]
Thank you this was my mistake, it is working fine now, I had a corrupt `ttf` font file in there. The `GridSplitter` control from the following package still shows an icon indicating that the grid handle icon is missing:

`<PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Layout" Version="7.1.100-dev.15.g12261e2626" />`

Do I need to include that icon in the `ttf` file, or does that package require to be recompiled?
