### ISSUE TITLE
Implicit template binding of ContentPresenter.Content does not work

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#857]
## I'm submitting a...
- Bug report

## Current behavior
When the template of a `ContentControl` is customized, nothing appear if we don't manually template bind the `Content` property of the `ContentPresenter`.

## Expected behavior
As of Windows, the `ContentPresenter.Content` property is implicit bound to its parent `ContentControl.Content`.

## Minimal reproduction of the problem with instructions
Override the default template of `ContentControl`
```xaml
<Style TargetType="ContentControl">
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="ContentControl">
                <ContentPresenter />
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

## Work-around
Explicitly template bind the `Content` property in your template:
```xaml
<Style TargetType="ContentControl">
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="ContentControl">
                <ContentPresenter Content="{TemplateBinding Content}" />
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

## Environment
Nuget Package: Uno.UI
Package Version(s): 1.45.0-dev.1450

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_ 
Relevant plugins: _none_

Related issue: #1621

**Comment by yowl** [comment]
I think this is fixed and the workaround is not necessary anymore, at least in Wasm.  In fact if you put the workaround, then the UWP head complains about the Content property for some reason.

**Comment by carldebilly** [comment]
Fixed by PR #1405

**Comment by jeromelaban** [comment]
Reopening this issue, it is not fixed.

Setting `FeatureConfiguration.ContentPresenter.UseImplicitContentFromTemplatedParent` to `true` restores the new behavior.

**Comment by FrancoisM** [comment]
Agreed not fixed.
Where do we set `FeatureConfiguration.ContentPresenter.UseImplicitContentFromTemplate` to `true`?

**Comment by davidjohnoliver** [comment]
@FrancoisM that's a static feature flag, you can set it, eg, in the constructor in `App.xaml.cs`:
```csharp
		public App()
		{
#if !NETFX_CORE
			Uno.UI.FeatureConfiguration.ContentPresenter.UseImplicitContentFromTemplatedParent = true;
#endif
```
